kind: pipeline
type: docker
name: default

steps:
  - name: push
    image: plugins/docker
    settings:
      mirror: tech2go.dev
      registry: tech2go.dev
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      debug: true
      dry_run: true
      repo: smalllu/caddy
      tags: [2.9-alpine]