kind: pipeline
type: docker
name: default

steps:
  - name: push
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: smalllu/caddy
      tags: [2.9-alpine]