name: Build and publish
on:
  push:
    branches:
      - main
jobs:
  build-and-publish:
    name: Build and publish image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: 'true'
          tags: smalllu/caddy:2.9-alpine